spring.application.name=Authentication


spring.datasource.url=jdbc:mysql://localhost:3306/authentication
spring.datasource.username=root
spring.datasource.password=Vishnu@21
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=vishnu
spring.security.user.password=vishnu@21
