spring.application.name=BillManagementSystem


spring.datasource.url=jdbc:mysql://localhost:3306/bill_management
spring.datasource.username=root
spring.datasource.password=Vishnu@21
spring.jpa.hibernate.ddl-auto=update