spring.application.name=GroceryBillManagement


spring.datasource.url=jdbc:mysql://localhost:3306/grocery_bill_management
spring.datasource.username=root
spring.datasource.password=Vishnu@21
spring.jpa.hibernate.ddl-auto=update