spring.application.name=CollegeManagement


spring.datasource.url=jdbc:mysql://localhost:3306/mtd_projects
spring.datasource.username=root
spring.datasource.password=Vishnu@21
spring.jpa.hibernate.ddl-auto=update
